apiVersion: apps/v1
kind: Deployment
metadata:
  name: petflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petflow-api
  template:
    metadata:
      labels:
        app: petflow-api
    spec:
      serviceAccountName: petflow-api
      containers:
        - name: petflow-api
          image: 160885257498.dkr.ecr.eu-central-1.amazonaws.com/petflow-api:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: petflow-secrets
          env:
            - name: AWS_REGION
              value: eu-central-1
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
