apiVersion: apps/v1
kind: Deployment
metadata:
  name: petflow-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: petflow-api
  template:
    metadata:
      labels:
        app: petflow-api
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: petflow-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - secretRef:
                name: petflow-secrets
          env:
            - name: AWS_REGION
              value: eu-central-1
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
